### ISSUE TITLE
Emacs nightly 28 produces unaligned menus

### ISSUE THREAD

**Issue by maikol-solis** [jimeh/emacs-builds#18] opened 2021-12-08 11:25 UTC
Hi! I installed this build from your repo

```
brew info emacs-app-nightly-28
emacs-app-nightly-28: 2021-12-06.da23e60.emacs-28
```

When I run

```
emacsclient -c -n -a ''
```

and pressing `SPC` in doom, I get unaligned menus

![image](https://user-images.githubusercontent.com/4078489/145200169-29d92ea5-32e3-4aa4-b199-09f602341e28.png)

![image](https://user-images.githubusercontent.com/4078489/145200463-dbbd7d47-4db5-4ab4-b329-9b4a8d89baea.png)

Thanks.

**Comment by jimeh** [comment] 2021-12-09 23:54
What version were you using previously? If it was Emacs 27.x it's possible it's a bug in doom-emacs with Emacs 28.x or later.

You can also try the 28.0.90 pretest build from here: https://github.com/jimeh/emacs-builds/releases/tag/Emacs-28.0.90-pretest

**Comment by maikol-solis** [comment] 2021-12-10 00:02
Hi! Yes I was using `emacs-mac` 27.2, and I haven't seen this behavior before. 
If I run emacs normally (not with `emacsclient`), everything works fine.

**Comment by jimeh** [comment] 2021-12-10 11:01
Ah, interesting. `emacs-mac` contains a bunch of custom macOS specific tweaks that isn't part of standard Emacs.

I doubt your issue is related to something specific I do with my builds, so I'd suggest trying the following to narrow down the issue:

- Try Emacs 27.2 from https://emacsformacosx.com
- Try my Emacs 27.2 build: https://github.com/jimeh/emacs-builds/releases/tag/Emacs-27.2
- Try the Emacs 28.0.90 pretest from https://emacsformacosx.com/builds
- Try my Emacs 28.0.90 pretest: https://github.com/jimeh/emacs-builds/releases/tag/Emacs-28.0.90-pretest
- Potentially also try latest nightly builds (29.x) from https://emacsformacosx.com/builds and my own builds.

**Comment by shmul** [comment] 2022-01-13 12:32
For what it is worth I'm experiencing similar behavior with 28.0.90 (202-12-13). `company-mode` popups are unaligned and so are go files that are automatically formatted by `gofmt`. I verified that 28.0.60 (2021-11-19) actually renders these perfectly.

Here is an example of a popup
![image](https://user-images.githubusercontent.com/701036/149330028-058ebf65-7f01-46df-a70a-9883880dbcef.png)

Here are two screenshots of the same file, one in emacs and opened in the terminal.
![image](https://user-images.githubusercontent.com/701036/149329839-28250f39-bc9b-424a-a9ee-d1b16b3d9cf3.png)
![image](https://user-images.githubusercontent.com/701036/149329876-e7a1a340-a74c-4ee5-8f52-cd9f152fd97a.png)

**Comment by jimeh** [comment] 2022-01-13 12:48
28.0.90 is the pretest build. Have you tried the 28.0.90 pretest build from https://emacsformacosx.com/builds to see if it exhibits similar behavior? If it does, it's definitely a bug with Emacs itself, rather than caused by any config/handling of my build process.

Also have you tried different fonts to see if it's specific fonts that causes the issue, or all fonts. Might also be worth trying to launch Emacs with `-Q` to skip all your config to see if it has the same issue.

Personally I've had an issue somewhat similar to this a handful of times over the past year. But it's very rare, and mostly has only happened after messing around with and changing themes/fonts a bunch in the running Emacs instance. Though I can't reliably re-produce it, as most of the time it's fine for months through hundreds of font/theme changes. But restarting Emacs always fixes the issue, and most of the time simply re-setting the same font against also fixes it.

**Comment by shmul** [comment] 2022-01-13 13:01
28.0.90 from https://emacsformacosx.com/builds works fine. Is it also with native compilation enabled? BTW, the issue I encountered isn't due to any fiddling with fonts or themes, as I did none of those for a while.

**Comment by jimeh** [comment] 2022-03-07 14:00
Apologies for the silence. I'm afraid I haven't managed to reproduce this myself at all. And the rare issue I mentioned in my last comment which I can't reliably re-produce, it hasn't happened a single time in a few months now.

Any chance you're willing to try one of the latest nightlies to see if the issue persists? If they do, I'd suggest maybe trying a different or minimal config. My best guess is your issues might be something common in your configs.

Over the years there's been a handful of times I've had to bit by bit comment out parts of my config to narrow down odd bugs to a specific package or setting that causes weird and unexpected side effects in unrelated areas.

@shmul As far as I know emacsformacosx.com builds do not have native compilation enabled, as it's not enabled by default when building Emacs.

**Comment by jimeh** [comment] 2022-03-08 15:33
Thanks @maikol-solis :)... I'll give @shmul a couple of days to confirm too before I close the issue.

**Closed** 2022-03-08 15:37 UTC
